### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate-lite#328]
There's some ambiguity between `substrate --light` and `substrate-lite` when pronounced.
It wouldn't be a bad idea to find a new name. People have suggested `smolstrate`, but I'm open to ideas.

**Comment by expenses** [comment]
`smolstrate` is cute

**Comment by andresilva** [comment]
Depending on the long term goals of this project it could make sense to bring it closer to polkadot rather than substrate (at least as it stands right now). In that case I'd suggest `smoldot`.

**Comment by tomaka** [comment]
Let's do some emoji-based voting by voting on this message. Multiple votes allowed.

- Keeping `substrate-lite`: :rocket: 
- `smolstrate`: :heart: 
- `smoldot`: :tada:

**Comment by tomaka** [comment]
https://github.com/paritytech/substrate-lite/pull/368
